#=========================================================================
# riscv.mk
#=========================================================================

riscv_srcs += \
  riscv-add.S \
  riscv-addi.S \
  riscv-bne.S \
  riscv-blt.S \
  riscv-jal.S \
  riscv-lui.S \
  riscv-lw.S \
  riscv-ori.S \
  riscv-sw.S \
  riscv-jr.S \
  riscv-and.S \
  riscv-andi.S \
  riscv-beq.S \
  riscv-bge.S \
  riscv-bgeu.S \
  riscv-bltu.S \
  riscv-div.S \
  riscv-divu.S \
  riscv-j.S \
  riscv-jalr.S \
  riscv-lb.S \
  riscv-lbu.S \
  riscv-lh.S \
  riscv-lhu.S \
  riscv-mul.S \
  riscv-or.S \
  riscv-rem.S \
  riscv-remu.S \
  riscv-sb.S \
  riscv-sh.S \
  riscv-sll.S \
  riscv-slli.S \
  riscv-slt.S \
  riscv-slti.S \
  riscv-sltiu.S \
  riscv-sltu.S \
  riscv-sra.S \
  riscv-srai.S \
  riscv-srl.S \
  riscv-srli.S \
  riscv-sub.S \
  riscv-xor.S \
  riscv-xori.S \
  riscv-vec.S \
  riscv-bmark-vvadd-scalar.S \
  riscv-bmark-vvadd-vector.S \
  riscv-bmark-daxpy-scalar.S \
  riscv-bmark-daxpy-vector.S \
  riscv-bmark-saxpy-scalar.S \
  riscv-bmark-saxpy-vector.S \
  riscv-bmark-linpack-scalar.S \
  riscv-bmark-linpack-vector.S \
  riscv-stride.S \
  riscv-redsum.S \
  riscv-bmark-daxpy-scalar-N16.S \
  riscv-bmark-daxpy-scalar-N32.S \
  riscv-bmark-daxpy-scalar-N64.S \
  riscv-bmark-daxpy-scalar-N128.S \
  riscv-bmark-daxpy-scalar-N256.S \
  riscv-bmark-daxpy-vector-N16.S \
  riscv-bmark-daxpy-vector-N32.S \
  riscv-bmark-daxpy-vector-N64.S \
  riscv-bmark-daxpy-vector-N128.S \
  riscv-bmark-daxpy-vector-N256.S \
  riscv-bmark-linpack-scalar-4x4.S \
  riscv-bmark-linpack-scalar-8x8.S \
  riscv-bmark-linpack-scalar-16x16.S \
  riscv-bmark-linpack-scalar-32x32.S \
  riscv-bmark-linpack-vector-4x4.S \
  riscv-bmark-linpack-vector-8x8.S \
  riscv-bmark-linpack-vector-16x16.S \
  riscv-bmark-linpack-vector-32x32.S \
  riscv-bmark-linpack-pipelined-16x16.S \
  riscv-bmark-chain-depth-6.S \
  riscv-bmark-chain-depth-5.S \
  riscv-bmark-chain-depth-4.S \
  riscv-bmark-chain-depth-3.S \
  riscv-bmark-chain-depth-2.S \
  riscv-bmark-chain-depth-1.S \
  riscv-bmark-dotprod-scalar.S \
  riscv-bmark-dotprod-vector.S \
  riscv-bmark-vvmul-scalar.S \
  riscv-bmark-vvmul-vector.S \
